# VaultCaddy GitHub Pages 配置

# 網站信息
title: VaultCaddy - AI文檔處理專家
description: 使用AI技術處理銀行對帳單、發票、收據等財務文檔
url: "https://vaultcaddy.github.io"
baseurl: "/vaultcaddy-app"

# 作者信息
author:
  name: VaultCaddy Team
  email: support@vaultcaddy.com

# GitHub Pages 設置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - "*.md"
  - "VAULTCADDY_*.md"
  - deploy-to-github.sh
  - EMERGENCY_FIX.js

# 包含文件
include:
  - .htaccess

# 設置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 默認值
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
