#!/bin/bash

echo "=== 查找 vaultcaddy@gmail.com 用户 ==="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 打开 Firebase Console"
echo "   https://console.firebase.google.com/project/vaultcaddy-production-cbbe2/firestore/data/~2Fusers"
echo ""
echo "2. 在 users 集合页面的右上角搜索框中输入："
echo "   email == vaultcaddy@gmail.com"
echo ""
echo "3. 查看搜索结果，记录用户的 ID 和 credits 字段"
echo ""
echo "4. 如果找不到任何结果，说明 users 集合中没有 vaultcaddy@gmail.com 用户"
echo "   这就是为什么 Credits 无法增加的原因！"
echo ""
echo "5. 告诉我："
echo "   - 是否找到了用户？"
echo "   - 用户 ID 是什么？"
echo "   - 当前 credits 是多少？"
