#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
创建所有剩余的Landing Pages
包括：优化2个 + 创建22个新的 = 共24个Landing Pages
"""

import os
import shutil

# 读取accountant模板
with open('solutions/accountant/index.html', 'r', encoding='utf-8') as f:
    template = f.read()

# 所有Landing Pages配置（第一批需要优化的 + 第二三四批新创建的）
LANDING_PAGES = {
    # 第一批 - 需要优化的2个
    'restaurant': {
        'title': '餐廳專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港 | 低至HK$0.5/頁',
        'description': '專為香港餐廳和餐飲業設計的AI銀行對帳單處理工具。自動處理食材採購、員工薪資、營業額記錄。10秒完成一份對帳單，98%準確率，支援所有香港銀行。月費HK$58起。',
        'keywords': '餐廳會計,餐飲財務管理,銀行對帳單,香港餐廳,食肆管理,QuickBooks,AI會計',
        'h1': '餐廳和餐飲業專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '每月處理上百筆食材採購、員工薪資記錄',
        'pain2': '現金和電子支付混合，對帳複雜',
        'pain3': '忙碌時間無法及時更新財務記錄',
        'solution1': '自動識別食材供應商、人力成本、營業收入分類',
        'solution2': '支援現金、信用卡、電子錢包混合對帳',
        'solution3': '10秒完成一份對帳單，節省90%時間',
        'case_company': '香港茶餐廳',
        'case_problem': '每月要處理50+供應商發票和對帳單，財務混亂',
        'case_solution': '使用VaultCaddy後，每月節省20小時，財務一目了然',
        'faq1_q': '支援哪些香港銀行？',
        'faq1_a': '支援所有香港主要銀行，包括匯豐、恆生、中銀、渣打、東亞、花旗、星展等。',
        'faq2_q': '能處理混合支付方式嗎？',
        'faq2_a': '是的！VaultCaddy能智能識別現金、信用卡、支付寶、WeChat Pay等所有支付方式，自動分類記帳。',
        'faq3_q': '我們有多家分店，可以統一管理嗎？',
        'faq3_a': '完全可以！您可以為每家分店創建獨立項目，也可以合併查看所有分店的財務報表。無限制項目數量。',
    },
    'retail-store': {
        'title': '零售店專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港 | 低至HK$0.5/頁',
        'description': '專為香港零售店和商鋪設計的AI銀行對帳單處理工具。自動處理進貨、銷售、庫存記錄。10秒完成一份對帳單，98%準確率，支援所有香港銀行。月費HK$58起。',
        'keywords': '零售店會計,商鋪財務,銀行對帳單,香港零售,QuickBooks,AI會計',
        'h1': '零售店和商鋪專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '每日大量小額交易，人工記帳耗時費力',
        'pain2': '進貨、銷售、退貨混在一起，難以分類',
        'pain3': '多種支付方式，對帳困難',
        'solution1': '自動識別進貨、銷售、退貨、運費等交易類型',
        'solution2': '支援信用卡、現金、電子支付混合對帳',
        'solution3': '即時生成銷售報表和利潤分析',
        'case_company': '香港時裝店',
        'case_problem': '每日處理100+筆交易，人工對帳要花3小時',
        'case_solution': '使用VaultCaddy後，10分鐘完成對帳，錯誤率降低95%',
        'faq1_q': '能處理退貨和換貨記錄嗎？',
        'faq1_a': '可以！VaultCaddy能自動識別退貨交易，並與原銷售記錄關聯，讓您清楚追蹤每筆退貨。',
        'faq2_q': '支援庫存管理嗎？',
        'faq2_a': '我們專注於財務記帳和對帳單處理。但可以與您現有的庫存系統數據整合，提供完整的財務視圖。',
        'faq3_q': '多店鋪如何管理？',
        'faq3_a': '每個店鋪可以創建獨立項目，也可以統一查看所有店鋪的財務數據。項目數量無限制。',
    },
    
    # 第二批（7個）
    'consultant': {
        'title': '顧問公司專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港管理顧問公司設計的AI銀行對帳單處理工具。自動處理項目收款、差旅費用、員工薪資。10秒完成一份對帳單，98%準確率。月費HK$58起。',
        'keywords': '顧問公司會計,管理顧問財務,銀行對帳單,香港顧問,QuickBooks',
        'h1': '顧問公司專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個項目同時進行，收支混亂難追蹤',
        'pain2': '差旅費用報銷流程複雜',
        'pain3': '客戶付款週期長，應收帳款管理困難',
        'solution1': '按項目自動分類收入和支出',
        'solution2': '一鍵整理差旅和業務費用',
        'solution3': '自動追蹤應收帳款狀態',
        'case_company': '香港管理顧問公司',
        'case_problem': '5個項目同時運作，財務記帳混亂',
        'case_solution': '使用VaultCaddy後，每個項目財務清晰可見，節省80%記帳時間',
        'faq1_q': '能按項目分類收支嗎？',
        'faq1_a': '可以！VaultCaddy支援自定義標籤，讓您按項目、客戶或任何方式分類財務記錄。',
        'faq2_q': '差旅費用如何處理？',
        'faq2_a': 'AI能自動識別差旅相關費用（機票、酒店、交通），並按項目歸類，方便報銷和成本控制。',
        'faq3_q': '支援多幣種嗎？',
        'faq3_a': '支援！自動識別和轉換多種貨幣，適合有國際業務的顧問公司。',
    },
    'designer': {
        'title': '設計師專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港設計師和設計工作室設計的AI銀行對帳單處理工具。自動處理項目收款、軟件訂閱、外包費用。月費HK$58起。',
        'keywords': '設計師會計,設計工作室財務,自由設計師,銀行對帳單,香港設計師',
        'h1': '設計師和設計工作室專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個項目並行，收款和支出難追蹤',
        'pain2': '軟件訂閱費、素材購買費用零散',
        'pain3': '與客戶對帳耗時，影響創作時間',
        'solution1': '按項目自動分類收入和開支',
        'solution2': '自動追蹤訂閱費和軟件授權',
        'solution3': '10秒生成客戶對帳單',
        'case_company': '香港UI/UX設計工作室',
        'case_problem': '10+並行項目，財務記錄混亂',
        'case_solution': '使用VaultCaddy後，每週節省5小時財務處理時間，專注設計',
        'faq1_q': '能追蹤項目收支嗎？',
        'faq1_a': '可以！按項目標籤分類所有收入和支出，實時查看每個項目的盈利情況。',
        'faq2_q': '訂閱費如何管理？',
        'faq2_a': 'AI自動識別Adobe、Figma等設計軟件的訂閱費，並提醒續費日期。',
        'faq3_q': '支援外包費用記錄嗎？',
        'faq3_a': '支援！自動識別支付給自由職業者和外包商的費用，方便成本控制。',
    },
    'developer': {
        'title': '開發者專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港開發者和軟件工程師設計的AI銀行對帳單處理工具。自動處理項目收款、雲端服務費用。月費HK$58起。',
        'keywords': '開發者會計,程序員財務,自由開發者,銀行對帳單,香港開發者',
        'h1': '開發者和程序員專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個外包項目，收款進度難追蹤',
        'pain2': 'AWS、GCP等雲端費用複雜難懂',
        'pain3': '技術工具訂閱費零散，缺乏統一管理',
        'solution1': '按項目自動分類收入',
        'solution2': '智能識別雲端服務費用明細',
        'solution3': '統一追蹤所有開發工具訂閱',
        'case_company': '香港全端開發者',
        'case_problem': '8個外包項目，AWS費用不清晰',
        'case_solution': '使用VaultCaddy後，每個項目成本一目了然，利潤提升15%',
        'faq1_q': '能識別雲端服務費用嗎？',
        'faq1_a': '可以！自動識別AWS、GCP、Azure、Heroku等雲端平台的費用，並按項目分攤。',
        'faq2_q': '訂閱管理功能如何？',
        'faq2_a': '自動追蹤GitHub、JetBrains、Notion等開發工具訂閱，提醒續費和優化開支。',
        'faq3_q': '適合接外包的開發者嗎？',
        'faq3_a': '非常適合！按項目追蹤收入和成本，清楚知道每個項目的真實利潤。',
    },
    'marketing-agency': {
        'title': '營銷公司專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港數碼營銷公司設計的AI銀行對帳單處理工具。自動處理廣告支出、客戶收款、外包費用。月費HK$58起。',
        'keywords': '營銷公司會計,廣告公司財務,數碼營銷,銀行對帳單,香港營銷',
        'h1': '營銷和廣告公司專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '廣告支出和客戶收款複雜，對帳困難',
        'pain2': '多個客戶項目同時進行，成本難分攤',
        'pain3': 'Facebook Ads、Google Ads等平台費用混亂',
        'solution1': '自動分類廣告支出和客戶收款',
        'solution2': '按客戶項目追蹤所有成本',
        'solution3': '智能識別各廣告平台費用',
        'case_company': '香港數碼營銷公司',
        'case_problem': '15個客戶，廣告支出和收入難對帳',
        'case_solution': '使用VaultCaddy後，每個客戶的ROI清晰可見，財務時間節省70%',
        'faq1_q': '能追蹤廣告支出嗎？',
        'faq1_a': '可以！自動識別Facebook Ads、Google Ads、LinkedIn等平台的廣告費用，並按客戶分類。',
        'faq2_q': '如何管理客戶項目財務？',
        'faq2_a': '為每個客戶創建獨立標籤，所有收入和支出自動歸類，實時查看項目盈利。',
        'faq3_q': '支援外包費用記錄嗎？',
        'faq3_a': '支援！自動識別支付給設計師、文案、攝影師等外包商的費用。',
    },
    'photographer': {
        'title': '攝影師專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港攝影師和攝影工作室設計的AI銀行對帳單處理工具。自動處理拍攝收款、器材購置、後期費用。月費HK$58起。',
        'keywords': '攝影師會計,攝影工作室財務,自由攝影師,銀行對帳單,香港攝影師',
        'h1': '攝影師和攝影工作室專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '婚禮、活動、商業拍攝收款進度難追蹤',
        'pain2': '器材、租借、後期外包費用零散',
        'pain3': '客戶訂金、尾款分批付款，記帳複雜',
        'solution1': '按拍攝項目自動分類收入',
        'solution2': '統一管理器材和服務費用',
        'solution3': '自動追蹤分期付款進度',
        'case_company': '香港婚禮攝影師',
        'case_problem': '每月20+婚禮項目，收款狀態混亂',
        'case_solution': '使用VaultCaddy後，每個項目收支清晰，減少忘記追款情況',
        'faq1_q': '能按拍攝項目分類嗎？',
        'faq1_a': '可以！為每個拍攝項目創建標籤，追蹤訂金、尾款和所有相關開支。',
        'faq2_q': '器材購置如何記錄？',
        'faq2_a': 'AI自動識別相機、鏡頭、燈光等器材購買記錄，方便資產管理和折舊計算。',
        'faq3_q': '分期付款如何管理？',
        'faq3_a': '自動追蹤客戶的訂金、中期款、尾款狀態，提醒收款進度。',
    },
    'property-manager': {
        'title': '物業管理專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港物業管理公司設計的AI銀行對帳單處理工具。自動處理租金收入、維修支出、管理費記錄。月費HK$58起。',
        'keywords': '物業管理會計,租金管理,銀行對帳單,香港物業,房地產財務',
        'h1': '物業管理公司專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個物業租金收入，人工對帳耗時',
        'pain2': '維修、保養、清潔費用分散',
        'pain3': '租客拖欠租金，追蹤困難',
        'solution1': '按物業自動分類租金收入',
        'solution2': '統一管理所有維修和運營費用',
        'solution3': '自動追蹤應收租金狀態',
        'case_company': '香港物業管理公司',
        'case_problem': '管理50個單位，租金對帳要花2天',
        'case_solution': '使用VaultCaddy後，10分鐘完成所有單位對帳，效率提升95%',
        'faq1_q': '能按物業分類收支嗎？',
        'faq1_a': '可以！為每個物業或單位創建標籤，自動追蹤租金收入和相關支出。',
        'faq2_q': '如何追蹤拖欠租金？',
        'faq2_a': 'AI自動對比預期租金和實際收款，標記拖欠情況，方便及時跟進。',
        'faq3_q': '維修費用如何管理？',
        'faq3_a': '自動識別維修、保養、清潔等費用，並按物業分攤，清楚掌握每個物業的淨收益。',
    },
    'startup': {
        'title': '初創公司專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港初創企業設計的AI銀行對帳單處理工具。自動處理營業收入、員工薪資、雲端服務費。月費HK$58起。',
        'keywords': '初創公司會計,startup財務,銀行對帳單,香港創業,QuickBooks',
        'h1': '初創公司和Startup專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '快速成長階段，交易量激增難管理',
        'pain2': '融資、營收、開支混在一起',
        'pain3': '創始團隊忙於業務，沒時間處理財務',
        'solution1': '自動分類所有收入和支出',
        'solution2': '實時掌握現金流和burn rate',
        'solution3': '一鍵生成給投資人的財務報表',
        'case_company': '香港SaaS初創公司',
        'case_problem': '融資後交易量暴增，財務混亂',
        'case_solution': '使用VaultCaddy後，財務透明，投資人信心大增，成功融資A輪',
        'faq1_q': '適合Pre-seed階段嗎？',
        'faq1_a': '非常適合！從第一天起就建立清晰的財務記錄，為未來融資做準備。',
        'faq2_q': '能追蹤現金流嗎？',
        'faq2_a': '可以！實時查看現金流狀態，計算runway，幫助做出正確的財務決策。',
        'faq3_q': '投資人要財務報表怎麼辦？',
        'faq3_a': '一鍵匯出QuickBooks格式或PDF報表，隨時提供給投資人和會計師。',
    },
    
    # 第三批（7個）
    'contractor': {
        'title': '承包商專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港裝修承包商和建築工程公司設計的AI銀行對帳單處理工具。自動處理項目收款、材料採購、工人薪資。月費HK$58起。',
        'keywords': '承包商會計,裝修財務,建築工程,銀行對帳單,香港承包商',
        'h1': '承包商和裝修公司專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個工程項目同時進行，財務混亂',
        'pain2': '材料採購和工人薪資支出複雜',
        'pain3': '客戶分期付款，追蹤困難',
        'solution1': '按工程項目自動分類收支',
        'solution2': '智能識別材料和人工成本',
        'solution3': '自動追蹤工程款項進度',
        'case_company': '香港裝修承包商',
        'case_problem': '5個工程並行，成本和收入難區分',
        'case_solution': '使用VaultCaddy後，每個工程的利潤清晰可見，避免虧本項目',
        'faq1_q': '能按工程項目分類嗎？',
        'faq1_a': '可以！為每個工程創建獨立標籤，追蹤所有材料、人工和收款記錄。',
        'faq2_q': '材料採購如何管理？',
        'faq2_a': 'AI自動識別五金、建材供應商的交易，並按工程分攤成本。',
        'faq3_q': '分期工程款如何追蹤？',
        'faq3_a': '自動記錄首期、進度款、尾款狀態，提醒收款時間，減少拖款風險。',
    },
    'fitness-coach': {
        'title': '健身教練專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港健身教練和私人教練設計的AI銀行對帳單處理工具。自動處理課程收費、會員費、器材費用。月費HK$58起。',
        'keywords': '健身教練會計,私人教練財務,銀行對帳單,香港健身,課程管理',
        'h1': '健身教練和私人教練專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個學員，課程費用收款混亂',
        'pain2': '月費、課程包、單次課程收費方式複雜',
        'pain3': '器材、場地租借費用零散',
        'solution1': '按學員自動分類課程收入',
        'solution2': '智能識別不同收費模式',
        'solution3': '統一管理所有運營開支',
        'case_company': '香港私人健身教練',
        'case_problem': '30+學員，收費記錄混亂常忘記',
        'case_solution': '使用VaultCaddy後，每個學員的付款狀態一目了然，收入增加20%',
        'faq1_q': '能追蹤學員付款嗎？',
        'faq1_a': '可以！為每個學員創建標籤，追蹤課程包、月費等所有付款記錄。',
        'faq2_q': '不同收費模式如何管理？',
        'faq2_a': 'AI自動識別月費、季費、年費、單次課程、課程包等各種收費模式。',
        'faq3_q': '場地費如何記錄？',
        'faq3_a': '自動識別健身房租金、場地費等開支，方便計算淨收入。',
    },
    'healthcare': {
        'title': '醫療診所專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港私家診所和醫療中心設計的AI銀行對帳單處理工具。自動處理診金收入、藥品採購、保險索償。月費HK$58起。',
        'keywords': '診所會計,醫療財務,私家診所,銀行對帳單,香港醫療,保險索償',
        'h1': '醫療診所和診療所專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '診金、藥費、保險索償收入複雜',
        'pain2': '藥品和醫療耗材採購記錄繁瑣',
        'pain3': '保險公司付款週期長，追蹤困難',
        'solution1': '自動分類診金、藥費、保險收入',
        'solution2': '智能管理醫療耗材採購記錄',
        'solution3': '追蹤保險索償狀態和應收款',
        'case_company': '香港私家診所',
        'case_problem': '每日100+病人，診金和保險索償記帳混亂',
        'case_solution': '使用VaultCaddy後，所有收入自動分類，保險應收帳款清晰可見',
        'faq1_q': '能處理保險索償嗎？',
        'faq1_a': '可以！自動追蹤每筆保險索償的狀態，提醒跟進未收款項目。',
        'faq2_q': '藥品採購如何管理？',
        'faq2_a': 'AI自動識別藥品供應商的交易，統一管理採購記錄和庫存成本。',
        'faq3_q': '符合醫療行業規定嗎？',
        'faq3_a': '完全符合！所有數據加密存儲，符合PDPO和醫療行業的隱私規定。',
    },
    'real-estate': {
        'title': '房地產代理專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港房地產代理和地產經紀設計的AI銀行對帳單處理工具。自動處理佣金收入、營銷開支、辦公費用。月費HK$58起。',
        'keywords': '地產代理會計,房地產財務,佣金管理,銀行對帳單,香港地產',
        'h1': '房地產代理和地產經紀專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '佣金收入不穩定，財務規劃困難',
        'pain2': '廣告、物業拍攝、推廣費用零散',
        'pain3': '與公司分成計算複雜',
        'solution1': '自動追蹤每筆交易的佣金收入',
        'solution2': '統一管理所有營銷和運營開支',
        'solution3': '智能計算分成和淨收入',
        'case_company': '香港資深地產代理',
        'case_problem': '收入不穩定，不知道真實盈利',
        'case_solution': '使用VaultCaddy後，清楚看到每月淨收入，財務規劃更有信心',
        'faq1_q': '能追蹤佣金收入嗎？',
        'faq1_a': '可以！為每筆交易創建記錄，自動計算佣金和分成，清楚掌握真實收入。',
        'faq2_q': '營銷費用如何管理？',
        'faq2_a': 'AI自動識別廣告、物業拍攝、網站費用等營銷開支，方便控制成本。',
        'faq3_q': '適合獨立代理嗎？',
        'faq3_a': '非常適合！清楚追蹤收入和支出，讓您知道何時該投資、何時該節省。',
    },
    'beauty-salon': {
        'title': '美容院專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港美容院和美容中心設計的AI銀行對帳單處理工具。自動處理療程收費、產品銷售、員工薪資。月費HK$58起。',
        'keywords': '美容院會計,美容中心財務,銀行對帳單,香港美容,療程管理',
        'h1': '美容院和美容中心專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '療程、產品、會員卡收入混合，難分類',
        'pain2': '美容產品採購和庫存管理複雜',
        'pain3': '員工提成計算繁瑣',
        'solution1': '自動分類療程收入和產品銷售',
        'solution2': '智能管理產品採購和庫存',
        'solution3': '按員工追蹤業績和提成',
        'case_company': '香港美容中心',
        'case_problem': '5位美容師，業績和提成計算混亂',
        'case_solution': '使用VaultCaddy後，每位員工業績清晰，提成計算準確，員工滿意度提升',
        'faq1_q': '能分類不同收入來源嗎？',
        'faq1_a': '可以！自動區分療程收入、產品銷售、會員卡收費，清楚掌握收入結構。',
        'faq2_q': '產品庫存如何管理？',
        'faq2_a': '追蹤產品採購記錄，幫助計算庫存成本和毛利率。',
        'faq3_q': '員工提成如何計算？',
        'faq3_a': '按員工標籤追蹤業績，方便計算提成和獎金。',
    },
    'cleaning-service': {
        'title': '清潔服務專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港清潔公司和家政服務設計的AI銀行對帳單處理工具。自動處理服務收費、清潔用品採購、員工薪資。月費HK$58起。',
        'keywords': '清潔公司會計,家政服務財務,銀行對帳單,香港清潔,服務管理',
        'h1': '清潔服務和家政公司專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個客戶和物業，收費記錄混亂',
        'pain2': '清潔用品採購和補貨頻繁',
        'pain3': '兼職員工薪資計算複雜',
        'solution1': '按客戶和物業自動分類收入',
        'solution2': '智能管理清潔用品採購記錄',
        'solution3': '自動計算員工工時和薪資',
        'case_company': '香港清潔服務公司',
        'case_problem': '50+物業客戶，收款和員工薪資記帳困難',
        'case_solution': '使用VaultCaddy後，每個客戶收款清晰，員工薪資計算準確',
        'faq1_q': '能按客戶分類嗎？',
        'faq1_a': '可以！為每個客戶或物業創建標籤，追蹤服務收費和相關成本。',
        'faq2_q': '清潔用品採購如何管理？',
        'faq2_a': 'AI自動識別清潔用品供應商交易，方便控制成本和安排補貨。',
        'faq3_q': '兼職員工薪資如何處理？',
        'faq3_a': '追蹤每次薪資支付記錄，方便計算真實人工成本。',
    },
    'travel-agent': {
        'title': '旅行社專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港旅行社和旅遊顧問設計的AI銀行對帳單處理工具。自動處理團費收入、機票酒店預訂、導遊費用。月費HK$58起。',
        'keywords': '旅行社會計,旅遊財務,銀行對帳單,香港旅行社,團費管理',
        'h1': '旅行社和旅遊顧問專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '團費收入和旅遊成本交錯，利潤難計算',
        'pain2': '機票、酒店、導遊等費用分散',
        'pain3': '客戶分期付款和退款處理複雜',
        'solution1': '按旅行團自動分類收入和成本',
        'solution2': '智能追蹤所有旅遊相關開支',
        'solution3': '自動處理分期和退款記錄',
        'case_company': '香港旅行社',
        'case_problem': '每月10+旅行團，收支混亂利潤不明',
        'case_solution': '使用VaultCaddy後，每個旅行團的利潤清晰可見，定價更精準',
        'faq1_q': '能按旅行團分類嗎？',
        'faq1_a': '可以！為每個旅行團創建標籤，追蹤團費收入和所有相關成本。',
        'faq2_q': '旅遊供應商費用如何管理？',
        'faq2_a': 'AI自動識別機票、酒店、交通、導遊等費用，並按旅行團歸類。',
        'faq3_q': '退款如何處理？',
        'faq3_a': '自動記錄退款交易，與原團費關聯，方便追蹤和對帳。',
    },
    
    # 第四批（8個）
    'artist': {
        'title': '藝術家專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港藝術家和創作者設計的AI銀行對帳單處理工具。自動處理作品銷售、展覽收入、材料費用。月費HK$58起。',
        'keywords': '藝術家會計,創作者財務,銀行對帳單,香港藝術家,作品銷售',
        'h1': '藝術家和創作者專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '作品銷售收入不穩定，財務規劃困難',
        'pain2': '藝術材料、工作室租金、展覽費用零散',
        'pain3': '與畫廊分成計算複雜',
        'solution1': '追蹤每件作品的銷售記錄',
        'solution2': '統一管理所有創作相關開支',
        'solution3': '智能計算畫廊分成和淨收入',
        'case_company': '香港獨立藝術家',
        'case_problem': '收入不穩定，不知道創作是否盈利',
        'case_solution': '使用VaultCaddy後，清楚看到每月收支，做出更好的創作決策',
        'faq1_q': '能追蹤作品銷售嗎？',
        'faq1_a': '可以！為每件作品創建記錄，追蹤銷售價格、分成和淨收入。',
        'faq2_q': '材料費用如何管理？',
        'faq2_a': 'AI自動識別顏料、畫布、雕塑材料等採購，方便計算創作成本。',
        'faq3_q': '展覽收入如何記錄？',
        'faq3_a': '按展覽標籤分類收入和費用，清楚掌握每次展覽的投資回報。',
    },
    'coworking-space': {
        'title': '共享辦公室專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港共享辦公空間和聯合辦公室設計的AI銀行對帳單處理工具。自動處理會員費、租金收入、運營開支。月費HK$58起。',
        'keywords': 'coworking會計,共享辦公財務,銀行對帳單,香港coworking,會員管理',
        'h1': '共享辦公室和Coworking專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '會員費、日租、月租收入方式複雜',
        'pain2': '多個會員同時使用，收款記錄混亂',
        'pain3': '運營成本高，需精準控制開支',
        'solution1': '自動分類不同收費模式',
        'solution2': '按會員追蹤付款狀態',
        'solution3': '實時掌握運營成本和盈利',
        'case_company': '香港共享辦公空間',
        'case_problem': '100+會員，收費模式多樣，對帳困難',
        'case_solution': '使用VaultCaddy後，每個會員付款清晰，拖欠率降低80%',
        'faq1_q': '能管理不同收費模式嗎？',
        'faq1_a': '可以！自動識別日租、月租、年費等不同收費，按會員分類記錄。',
        'faq2_q': '運營成本如何追蹤？',
        'faq2_a': 'AI自動分類租金、水電、網絡、清潔等運營開支，方便成本控制。',
        'faq3_q': '適合小型coworking嗎？',
        'faq3_a': '非常適合！從幾個會員到上百個會員，都能輕鬆管理財務。',
    },
    'delivery-driver': {
        'title': '外送司機專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港外送司機和配送員設計的AI銀行對帳單處理工具。自動處理外送收入、燃油費、車輛維護費。月費HK$58起。',
        'keywords': '外送司機會計,配送員財務,銀行對帳單,香港外送,foodpanda,deliveroo',
        'h1': '外送司機和配送員專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': 'Foodpanda、Deliveroo等多平台收入難統計',
        'pain2': '燃油費、維修費、停車費零散難追蹤',
        'pain3': '不知道真實時薪和淨收入',
        'solution1': '統一追蹤所有平台收入',
        'solution2': '自動分類燃油和車輛相關開支',
        'solution3': '計算真實時薪和淨利潤',
        'case_company': '香港全職外送司機',
        'case_problem': '3個平台同時跑，不知道真實收入',
        'case_solution': '使用VaultCaddy後，看到真實時薪，優化接單策略，收入增加25%',
        'faq1_q': '能追蹤多個平台嗎？',
        'faq1_a': '可以！統一追蹤Foodpanda、Deliveroo、UberEats等所有平台收入。',
        'faq2_q': '燃油費如何記錄？',
        'faq2_a': 'AI自動識別加油站交易，方便計算燃油成本和里程效益。',
        'faq3_q': '能計算真實時薪嗎？',
        'faq3_a': '根據收入和所有開支，自動計算您的真實時薪和月淨收入。',
    },
    'event-planner': {
        'title': '活動策劃專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港活動策劃公司和婚禮統籌設計的AI銀行對帳單處理工具。自動處理活動收入、供應商費用、客戶訂金。月費HK$58起。',
        'keywords': '活動策劃會計,婚禮統籌財務,銀行對帳單,香港活動,event planning',
        'h1': '活動策劃和婚禮統籌專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多個活動同時進行，預算和開支混亂',
        'pain2': '供應商費用多樣，對帳複雜',
        'pain3': '客戶分期付款，追蹤困難',
        'solution1': '按活動自動分類收入和開支',
        'solution2': '統一管理所有供應商費用',
        'solution3': '自動追蹤客戶付款進度',
        'case_company': '香港婚禮統籌公司',
        'case_problem': '每月10+婚禮，預算和實際開支常超支',
        'case_solution': '使用VaultCaddy後，每場活動預算清晰，超支情況減少90%',
        'faq1_q': '能按活動分類嗎？',
        'faq1_a': '可以！為每場活動創建標籤，追蹤所有收入和開支，實時掌握預算狀態。',
        'faq2_q': '供應商費用如何管理？',
        'faq2_a': 'AI自動識別場地、餐飲、佈置、攝影等供應商費用，並按活動歸類。',
        'faq3_q': '分期付款如何追蹤？',
        'faq3_a': '自動記錄訂金、進度款、尾款狀態，提醒收款時間。',
    },
    'musician': {
        'title': '音樂人專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港音樂人和樂隊設計的AI銀行對帳單處理工具。自動處理演出收入、版權費、器材購置費用。月費HK$58起。',
        'keywords': '音樂人會計,樂隊財務,銀行對帳單,香港音樂,版權收入',
        'h1': '音樂人和樂隊專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '演出、版權、串流等收入來源多樣',
        'pain2': '樂器、錄音、巡演費用零散',
        'pain3': '樂隊成員分成計算複雜',
        'solution1': '自動分類不同收入來源',
        'solution2': '統一管理所有音樂相關開支',
        'solution3': '智能計算成員分成',
        'case_company': '香港獨立樂隊',
        'case_problem': '收入來源多，成員分成常有爭議',
        'case_solution': '使用VaultCaddy後，所有收支透明，成員關係更和諧',
        'faq1_q': '能追蹤版權收入嗎？',
        'faq1_a': '可以！自動識別Spotify、Apple Music、KKBOX等串流平台的版權收入。',
        'faq2_q': '演出收入如何管理？',
        'faq2_a': '按演出場次標籤分類收入和相關開支，清楚掌握每場演出的盈利。',
        'faq3_q': '成員分成如何計算？',
        'faq3_a': '設定分成比例後，自動計算每位成員應得金額，透明公正。',
    },
    'nonprofit': {
        'title': '非牟利組織專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港慈善機構和NGO設計的AI銀行對帳單處理工具。自動處理捐款收入、項目開支、資助金記錄。月費HK$58起。',
        'keywords': 'NGO會計,慈善機構財務,銀行對帳單,香港非牟利,捐款管理',
        'h1': '非牟利組織和慈善機構專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '捐款、資助金、項目收入需嚴格追蹤',
        'pain2': '項目開支需要詳細記錄供審計',
        'pain3': '捐款者要求透明財務報告',
        'solution1': '自動分類捐款和資助金來源',
        'solution2': '按項目追蹤所有開支明細',
        'solution3': '一鍵生成審計報告',
        'case_company': '香港社區服務NGO',
        'case_problem': '5個項目，捐款和開支記錄混亂',
        'case_solution': '使用VaultCaddy後，每個項目財務透明，成功獲得更多資助',
        'faq1_q': '符合審計要求嗎？',
        'faq1_a': '完全符合！所有交易記錄清晰，可隨時匯出給會計師和審計師。',
        'faq2_q': '能按項目分類嗎？',
        'faq2_a': '可以！為每個項目創建標籤，追蹤專項資助和對應開支。',
        'faq3_q': '捐款者要報告怎麼辦？',
        'faq3_a': '一鍵生成財務報告，清楚展示每筆捐款的使用情況。',
    },
    'personal-finance': {
        'title': '個人理財專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港個人和家庭理財設計的AI銀行對帳單處理工具。自動分類收入支出，智能預算管理。月費HK$58起。',
        'keywords': '個人理財,家庭財務,銀行對帳單,香港理財,預算管理',
        'h1': '個人和家庭理財專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '多張信用卡、銀行卡，支出難追蹤',
        'pain2': '不知道錢花在哪裡',
        'pain3': '想存錢但總是失敗',
        'solution1': '自動統一所有帳戶交易',
        'solution2': '智能分類每筆支出',
        'solution3': '設定預算並自動提醒',
        'case_company': '香港雙職家庭',
        'case_problem': '每月超支不知道原因',
        'case_solution': '使用VaultCaddy後，發現外賣支出過高，調整後每月節省HK$3,000',
        'faq1_q': '個人用戶可以使用嗎？',
        'faq1_a': '當然可以！VaultCaddy也非常適合個人和家庭管理日常財務。',
        'faq2_q': '能設定預算嗎？',
        'faq2_a': '可以為不同支出類別設定預算，超支時自動提醒。',
        'faq3_q': '數據安全嗎？',
        'faq3_a': '絕對安全！銀行級別加密，只有您能看到自己的財務數據。',
    },
    'pet-service': {
        'title': '寵物服務專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港',
        'description': '專為香港寵物店、寵物美容和寵物托管設計的AI銀行對帳單處理工具。自動處理服務收費、用品採購、員工薪資。月費HK$58起。',
        'keywords': '寵物店會計,寵物美容財務,銀行對帳單,香港寵物,服務管理',
        'h1': '寵物服務和寵物店專用',
        'subtitle': 'AI智能銀行對帳單處理',
        'pain1': '美容、托管、用品銷售收入混合',
        'pain2': '寵物用品和食品採購頻繁',
        'pain3': '會員卡和散客收費方式不同',
        'solution1': '自動分類服務和產品銷售',
        'solution2': '智能管理用品採購和庫存',
        'solution3': '按客戶追蹤付款記錄',
        'case_company': '香港寵物美容店',
        'case_problem': '服務和產品銷售混在一起，利潤不清楚',
        'case_solution': '使用VaultCaddy後，清楚看到各項服務和產品的利潤率，優化定價',
        'faq1_q': '能分類不同服務嗎？',
        'faq1_a': '可以！自動區分美容、托管、訓練、產品銷售等不同收入來源。',
        'faq2_q': '用品採購如何管理？',
        'faq2_a': 'AI自動識別寵物食品、用品供應商的交易，方便庫存和成本管理。',
        'faq3_q': '會員制如何處理？',
        'faq3_a': '按客戶標籤追蹤會員卡、套餐、單次服務等不同付款方式。',
    },
}

def create_landing_page(slug, config):
    """創建一個landing page"""
    
    # 創建目錄
    page_dir = f'solutions/{slug}'
    os.makedirs(page_dir, exist_ok=True)
    
    # 基於模板創建新頁面
    new_content = template
    
    # 替換基本信息
    new_content = new_content.replace(
        '<title>會計師專用銀行對帳單處理工具 | VaultCaddy AI 自動化 | 香港 | 低至HK$0.5/頁</title>',
        f'<title>{config["title"]}</title>'
    )
    new_content = new_content.replace(
        'content="專為香港會計師事務所設計的AI銀行對帳單處理工具。支援匯豐、恆生、中銀、渣打等所有香港銀行。10秒完成一份對帳單，98%準確率，一鍵匯出QuickBooks/Xero。已服務200+香港會計師。月費HK$58起。"',
        f'content="{config["description"]}"'
    )
    new_content = new_content.replace(
        'content="會計師工具,銀行對帳單處理,CPA工具,會計事務所軟件,QuickBooks,Xero,AI會計,香港會計師,自動化會計,文檔處理"',
        f'content="{config["keywords"]}"'
    )
    
    # 替換URL
    new_content = new_content.replace(
        'https://vaultcaddy.com/solutions/accountant/',
        f'https://vaultcaddy.com/solutions/{slug}/'
    )
    new_content = new_content.replace(
        'href="../../auth.html"',
        'href="../../auth.html"'  # 保持不變
    )
    
    # 替換H1和副標題
    new_content = new_content.replace(
        '<h1 class="hero-title">會計師事務所專用<br><span class="highlight-gradient">AI智能銀行對帳單處理</span></h1>',
        f'<h1 class="hero-title">{config["h1"]}<br><span class="highlight-gradient">{config["subtitle"]}</span></h1>'
    )
    
    # 保存文件
    with open(f'{page_dir}/index.html', 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    return page_dir

def main():
    print("🚀 開始創建所有Landing Pages...")
    print("=" * 70)
    
    created_count = 0
    
    for slug, config in LANDING_PAGES.items():
        page_dir = create_landing_page(slug, config)
        created_count += 1
        print(f"✅ 創建: {page_dir}")
    
    print("=" * 70)
    print(f"🎉 完成！共創建 {created_count} 個Landing Pages")
    print(f"\n📋 創建的頁面:")
    for i, slug in enumerate(LANDING_PAGES.keys(), 1):
        print(f"   {i}. solutions/{slug}/")
    
    print("\n✅ 所有Landing Pages已創建完成！")

if __name__ == '__main__':
    main()

