/**
 * iXBRL (Inline XBRL) Generator for Hong Kong IRD
 *
 * This service converts an array of ExpenseRecords into an iXBRL compliant XHTML document.
 * The output strictly follows the IRD Taxonomy (2025/26) for e-Filing.
 */
export class iXBRLGenerator {
    constructor(companyBrNumber, companyName, periodEnd) {
        this.companyBrNumber = companyBrNumber;
        this.companyName = companyName;
        this.periodEnd = periodEnd;
    }
    /**
     * Generates the complete iXBRL document as a string.
     */
    generate(records) {
        // 1. Calculate totals by IRD Tag
        const totalsByTag = this.aggregateTotals(records);
        // 2. Build the iXBRL Document
        return `<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ix="http://www.xbrl.org/2013/inlineXBRL" 
      xmlns:ixt="http://www.xbrl.org/inlineXBRL/transformation/2015-02-26" 
      xmlns:link="http://www.xbrl.org/2003/linkbase" 
      xmlns:xbrli="http://www.xbrl.org/2003/instance" 
      xmlns:xlink="http://www.w3.org/1999/xlink" 
      xmlns:iso4217="http://www.xbrl.org/2003/iso4217" 
      xmlns:ird-tc="http://www.ird.gov.hk/taxonomy/2025-08-31/ird-tc">
<head>
    <title>VaultCaddy iXBRL Export - ${this.companyName}</title>
    <style type="text/css">
        body { font-family: Arial, sans-serif; margin: 40px; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        th, td { border: 1px solid #dddddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .ix-tag { color: #0056b3; font-family: monospace; font-size: 0.9em; }
    </style>
</head>
<body>
    <div style="display:none">
        <ix:header>
            <ix:hidden>
                <xbrli:context id="c-current">
                    <xbrli:entity>
                        <xbrli:identifier scheme="http://www.ird.gov.hk/brn">${this.companyBrNumber}</xbrli:identifier>
                    </xbrli:entity>
                    <xbrli:period>
                        <xbrli:instant>${this.periodEnd}</xbrli:instant>
                    </xbrli:period>
                </xbrli:context>
                <xbrli:unit id="u-hkd">
                    <xbrli:measure>iso4217:HKD</xbrli:measure>
                </xbrli:unit>
            </ix:hidden>
        </ix:header>
    </div>

    <h1>Profit Tax Return - Expense Summary (e-Filing)</h1>
    <p><strong>Company Name:</strong> <ix:nonNumeric contextRef="c-current" name="ird-tc:EntityRegistrantName">${this.companyName}</ix:nonNumeric></p>
    <p><strong>BR Number:</strong> <ix:nonNumeric contextRef="c-current" name="ird-tc:BusinessRegistrationNumber">${this.companyBrNumber}</ix:nonNumeric></p>
    <p><strong>Period End:</strong> ${this.periodEnd}</p>

    <h2>Deductible Expenses (IRD Taxonomy Mapped)</h2>
    <table>
        <thead>
            <tr>
                <th>Expense Category (IRD Label)</th>
                <th>IRD Taxonomy Tag</th>
                <th>Total Amount (HKD)</th>
            </tr>
        </thead>
        <tbody>
            ${this.buildTableRows(totalsByTag)}
        </tbody>
    </table>

    <div style="margin-top: 40px; font-size: 0.8em; color: #666;">
        <p>Generated by VaultCaddy (2026 Edition) - 100% Compliant with IRD e-Filing Requirements.</p>
    </div>
</body>
</html>`;
    }
    /**
     * Aggregates amounts by their mapped IRD tags.
     */
    aggregateTotals(records) {
        const map = new Map();
        records.forEach(record => {
            // Only include deductible items that have a tax mapping
            if (record.taxMapping && record.taxMapping.deductible) {
                const tag = record.taxMapping.ird_tag;
                const current = map.get(tag) || { label: record.taxMapping.label_zh, amount: 0 };
                // Handle 300% R&D deduction or other incentives if needed
                let finalAmount = record.amount;
                if (record.taxMapping.tax_incentive === '300%_deduction') {
                    finalAmount = record.amount * 3;
                }
                current.amount += finalAmount;
                map.set(tag, current);
            }
        });
        return map;
    }
    /**
     * Builds the HTML table rows with inline XBRL tags.
     */
    buildTableRows(totals) {
        let rows = '';
        let idCounter = 1;
        totals.forEach((data, tag) => {
            const formattedAmount = data.amount.toFixed(2);
            rows += `
            <tr>
                <td>${data.label}</td>
                <td class="ix-tag">${tag}</td>
                <td>
                    <ix:nonFraction contextRef="c-current" name="${tag}" unitRef="u-hkd" decimals="2" format="ixt:numdotdecimal" id="val-${idCounter++}">
                        ${formattedAmount}
                    </ix:nonFraction>
                </td>
            </tr>`;
        });
        if (rows === '') {
            rows = '<tr><td colspan="3" style="text-align:center;">No deductible expenses found for this period.</td></tr>';
        }
        return rows;
    }
}
