#!/bin/bash

# 基于日文版创建简洁的中文和英文版本

echo "🔄 开始创建简洁版本..."
echo ""

# 1. 创建中文版
echo "📝 翻译中文版..."
FILE="account.html"

sed -i '' 's/<html lang="zh-TW">/<html lang="zh-TW">/' "$FILE"
sed -i '' 's/アカウント設定/帳戶設定/g' "$FILE"
sed -i '' 's/VaultCaddy明細書変換/VaultCaddy明細書變換/g' "$FILE"
sed -i '' 's/>機能</>功能</g' "$FILE"
sed -i '' 's/>価格</>價格</g' "$FILE"
sed -i '' 's/>ダッシュボード</>儀表板</g' "$FILE"
sed -i '' 's/>ホーム</>首頁</g' "$FILE"
sed -i '' 's/>アカウント</>帳戶</g' "$FILE"
sed -i '' 's/>請求</>計費</g' "$FILE"
sed -i '' 's/>ログアウト</>登出</g' "$FILE"
sed -i '' 's/プロフィールとアカウントの設定を管理/管理您的個人資料和帳戶偏好設定/g' "$FILE"
sed -i '' 's/>プロフィール</>個人資料</g' "$FILE"
sed -i '' 's/現在のプラン/目前計劃/g' "$FILE"
sed -i '' 's/プランをアップグレード/升級計劃/g' "$FILE"
sed -i '' 's/サブスクリプション管理/管理訂閱/g' "$FILE"
sed -i '' 's/次回請求/下次計費/g' "$FILE"
sed -i '' 's/クレジット使用状況/Credits 使用情況/g' "$FILE"
sed -i '' 's/1ページ処理ごとに1クレジット消費/每處理 1 頁文檔消耗 1 個 Credit/g' "$FILE"
sed -i '' 's/超過分請求/超額計費/g' "$FILE"
sed -i '' 's/月間上限を超えた場合、自動的に/超出月度額度後自動按/g' "$FILE"
sed -i '' 's/¥10\/ページ/HKD \$0.5\/頁/g' "$FILE"
sed -i '' 's/で請求されます/計費/g' "$FILE"
sed -i '' 's/リセット日/重置日期/g' "$FILE"
sed -i '' 's/クレジット購入/購買 Credits/g' "$FILE"
sed -i '' 's/履歴を表示/查看記錄/g' "$FILE"
sed -i '' 's/>パスワード</>密碼</g' "$FILE"
sed -i '' 's/現在のパスワード/目前密碼/g' "$FILE"
sed -i '' 's/新しいパスワード/新密碼/g' "$FILE"
sed -i '' 's/パスワードは8文字以上必要です/密碼至少需要 8 個字元/g' "$FILE"
sed -i '' 's/新しいパスワードを確認/確認新密碼/g' "$FILE"
sed -i '' 's/パスワードを更新/更新密碼/g' "$FILE"
sed -i '' 's/購入履歴/購買記錄/g' "$FILE"
sed -i '' 's/全記録/所有記錄/g' "$FILE"
sed -i '' 's/>日付</>日期</g' "$FILE"
sed -i '' 's/>説明</>描述</g' "$FILE"
sed -i '' 's/記録を読み込み中\.\.\./載入記錄中.../g' "$FILE"
sed -i '' 's/危険エリア/危險區域/g' "$FILE"
sed -i '' 's/アカウントを削除すると、プロジェクト、ファイル、設定を含むすべてのデータが完全に削除されます。この操作は元に戻せません。/刪除您的帳戶將永久移除所有資料，包括項目、文檔和設定。此操作無法復原。/g' "$FILE"
sed -i '' 's/アカウントを削除/刪除帳戶/g' "$FILE"
sed -i '' 's/新しいプロジェクトを作成/創建新項目/g' "$FILE"
sed -i '' 's/プロジェクト名を入力して新しいドキュメントプロジェクトを作成/輸入項目名稱以創建新的文檔項目/g' "$FILE"
sed -i '' 's/プロジェクト名/項目名稱/g' "$FILE"
sed -i '' 's/>キャンセル</>取消</g' "$FILE"
sed -i '' 's/>作成</>創建</g' "$FILE"
sed -i '' 's/プライバシーポリシー/隱私政策/g' "$FILE"
sed -i '' 's/利用規約/服務條款/g' "$FILE"

echo "   ✅ 中文版完成"

# 2. 创建英文版
echo "📝 翻译英文版..."
FILE="en/account.html"

sed -i '' 's/<html lang="zh-TW">/<html lang="en">/' "$FILE"
sed -i '' 's/アカウント設定/Account Settings/g' "$FILE"
sed -i '' 's/VaultCaddy明細書変換/VaultCaddy Statement Converter/g' "$FILE"
sed -i '' 's/>機能</>Features</g' "$FILE"
sed -i '' 's/>価格</>Pricing</g' "$FILE"
sed -i '' 's/>ダッシュボード</>Dashboard</g' "$FILE"
sed -i '' 's/>ホーム</>Home</g' "$FILE"
sed -i '' 's/>アカウント</>Account</g' "$FILE"
sed -i '' 's/>請求</>Billing</g' "$FILE"
sed -i '' 's/>ログアウト</>Logout</g' "$FILE"
sed -i '' 's/プロフィールとアカウントの設定を管理/Manage your profile and account preferences/g' "$FILE"
sed -i '' 's/>プロフィール</>Profile</g' "$FILE"
sed -i '' 's/現在のプラン/Current Plan/g' "$FILE"
sed -i '' 's/プランをアップグレード/Upgrade Plan/g' "$FILE"
sed -i '' 's/サブスクリプション管理/Manage Subscription/g' "$FILE"
sed -i '' 's/次回請求/Next Billing/g' "$FILE"
sed -i '' 's/クレジット使用状況/Credits Usage/g' "$FILE"
sed -i '' 's/1ページ処理ごとに1クレジット消費/1 Credit is consumed per page processed/g' "$FILE"
sed -i '' 's/超過分請求/Overage Billing/g' "$FILE"
sed -i '' 's/月間上限を超えた場合、自動的に/Additional pages beyond monthly quota automatically billed at/g' "$FILE"
sed -i '' 's/¥10\/ページ/HKD \$0.5\/page/g' "$FILE"
sed -i '' 's/で請求されます//g' "$FILE"
sed -i '' 's/リセット日/Reset Date/g' "$FILE"
sed -i '' 's/クレジット購入/Purchase Credits/g' "$FILE"
sed -i '' 's/履歴を表示/View History/g' "$FILE"
sed -i '' 's/>パスワード</>Password</g' "$FILE"
sed -i '' 's/現在のパスワード/Current Password/g' "$FILE"
sed -i '' 's/新しいパスワード/New Password/g' "$FILE"
sed -i '' 's/パスワードは8文字以上必要です/Password must be at least 8 characters/g' "$FILE"
sed -i '' 's/新しいパスワードを確認/Confirm New Password/g' "$FILE"
sed -i '' 's/パスワードを更新/Update Password/g' "$FILE"
sed -i '' 's/購入履歴/Purchase History/g' "$FILE"
sed -i '' 's/全記録/All Records/g' "$FILE"
sed -i '' 's/>日付</>Date</g' "$FILE"
sed -i '' 's/>説明</>Description</g' "$FILE"
sed -i '' 's/記録を読み込み中\.\.\./Loading records.../g' "$FILE"
sed -i '' 's/危険エリア/Danger Zone/g' "$FILE"
sed -i '' 's/アカウントを削除すると、プロジェクト、ファイル、設定を含むすべてのデータが完全に削除されます。この操作は元に戻せません。/Deleting your account will permanently remove all data, including projects, documents, and settings. This action cannot be undone./g' "$FILE"
sed -i '' 's/アカウントを削除/Delete Account/g' "$FILE"
sed -i '' 's/新しいプロジェクトを作成/Create New Project/g' "$FILE"
sed -i '' 's/プロジェクト名を入力して新しいドキュメントプロジェクトを作成/Enter project name to create a new document project/g' "$FILE"
sed -i '' 's/プロジェクト名/Project Name/g' "$FILE"
sed -i '' 's/>キャンセル</>Cancel</g' "$FILE"
sed -i '' 's/>作成</>Create</g' "$FILE"
sed -i '' 's/プライバシーポリシー/Privacy Policy/g' "$FILE"
sed -i '' 's/利用規約/Terms of Service/g' "$FILE"

echo "   ✅ 英文版完成"

echo ""
echo "🎉 简洁版本创建完成！"
echo ""
echo "📊 验证结果："
echo "中文版行数: $(wc -l < account.html)"
echo "英文版行数: $(wc -l < en/account.html)"
echo "日文版行数: $(wc -l < jp/account.html)"

